services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
      interval: 10s 
  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - '7777:7777'
    expose:
      - '7777'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/actuator/health"]
      interval: 10s 
    environment:
      - EUREKA_SERVICE_URL=http://eureka-server:9999/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
  gateway-service-g:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s 
    environment:
      - EUREKA_SERVICE_URL=http://eureka-server:9999/eureka/
      - CONFIG_SERVER=http://config-server:7777
    depends_on:
      config-server:
        condition: service_healthy
  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - '1111:1111'
    expose:
      - '1111'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1111/actuator/health"]
      interval: 10s
    environment:
      - EUREKA_SERVICE_URL=http://eureka-server:9999/eureka/
      - CONFIG_SERVER=http://config-server:7777
    depends_on:
      gateway-service-g:
        condition: service_healthy
  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - '3333:3333'
    expose:
      - '3333'
    environment:
      - EUREKA_SERVICE_URL=http://eureka-server:9999/eureka/
      - CONFIG_SERVER=http://config-server:7777
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/actuator/health"]
      interval: 10s
    depends_on:
      customer-service:
        condition: service_healthy
      
